In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!ls

drive  sample_data


In [ ]:
#!unzip /content/drive/MyDrive/Hack_Sochi/train_dataset_train.zip -d /content/drive/MyDrive/Hack_Sochi/

In [112]:
!unzip /content/drive/MyDrive/Hack_Sochi/test_dataset_test.zip -d /content/drive/MyDrive/Hack_Sochi/

Archive:  /content/drive/MyDrive/Hack_Sochi/test_dataset_test.zip
   creating: /content/drive/MyDrive/Hack_Sochi/test/
  inflating: /content/drive/MyDrive/Hack_Sochi/test/test.csv  
  inflating: /content/drive/MyDrive/Hack_Sochi/__MACOSX/test/._test.csv  
  inflating: /content/drive/MyDrive/Hack_Sochi/test/sample_submission.csv  
  inflating: /content/drive/MyDrive/Hack_Sochi/__MACOSX/test/._sample_submission.csv  


In [115]:
!ls /content/drive/MyDrive/Hack_Sochi/test

sample_submission.csv  test.csv


### Файл cntrbtrs.csv - счета и типы пенсионных схем

In [116]:
import pandas as pd
import numpy as np

In [118]:
 test = pd.read_csv('/content/drive/MyDrive/Hack_Sochi/test/test.csv')

In [119]:
test.head()

slctn_nmbr                           client_id  \
0           0  0x589BC912CB844D468212ADD42EAE4151   
1           2  0xCCF22420C90AE4459A25781A9A30F445   
2           3  0x943D2C768A4FB38311E6605EEA2B9E4A   
3           2  0x99E64FD29CC3B04189C5C9EBEAF6F9A4   
4           0  0x654EEEBA731C4A4881816631229C5B65   

                       npo_account_id  npo_accnts_nmbr  pmnts_type  year  \
0  0xAA9E8DDF1310724995598EA2B42D7D87                2           1  2017   
1  0x3B9B09857D152F468A42C5DEE6D723F7                1           3  2021   
2  0xA7F12C768A4FB38311E835E4A7632E00                1           2  2015   
3  0xBFE4BDFBE0E037478C29BA4F38121B15                1           1  2015   
4  0x4B5C7804E403C842B4ECBF69BC3EDD7C                2           1  2011   

  quarter  gender  age  clnt_cprtn_time_d  actv_prd_d  lst_pmnt_rcnc_d  \
0  2017Q2       1   54               6595        4543               31   
1  2021Q4       1   75               7078           0             2209   
2  2015Q3       1   35               1675        1615               29   
3  2015Q3       1   50               5180        3538               30   
4  2011Q3      -1   46                296         276               30   

     balance  oprtn_sum_per_qrtr  oprtn_sum_per_year frst_pmnt_date  \
0  464770.58            10880.44            39763.52     2004-12-31   
1     221.24               10.54               10.54     2015-12-14   
2   27071.14             1850.63             8540.05     2011-04-13   
3   50580.42             1219.51             6860.62     2005-12-31   
4    7300.73             1747.83             9468.41     2010-12-09   

  lst_pmnt_date_per_qrtr  frst_pmnt  lst_pmnt  pmnts_sum  pmnts_nmbr  \
0             2017-06-09   19164.90   4168.46  342134.88         151   
1                    NaN      82.48     82.48      82.48           1   
2             2015-09-14     301.96    948.37   24972.87          54   
3             2015-09-08    8455.28    406.50   31951.22         118   
4             2011-09-11     301.83   1353.97    7299.96          10   

   pmnts_sum_per_qrtr  pmnts_sum_per_year  pmnts_nmbr_per_qrtr  \
0            10880.43            39763.52                    3   
1               -0.00               -0.00                    0   
2             1850.63             6401.21                    3   
3             1219.51             4878.04                    3   
4             1747.83             9220.26                    3   

   pmnts_nmbr_per_year   incm_sum  incm_per_qrtr  incm_per_year  \
0                   11  122635.69          -0.00          -0.00   
1                    0     138.75          10.53          10.53   
2                   10    2098.26          -0.00        2138.83   
3                   12   13909.69          -0.00        1982.57   
4                   12       0.76          -0.00         248.13   

   mgd_accum_period  mgd_payment_period  phone_number  email  lk  \
0               0.0                 0.0            -1      0   1   
1               5.0                 5.0            -1     -1  -1   
2               0.0                 0.0             0      0  -1   
3               4.0                 4.0            -1     -1  -1   
4               0.0                 0.0            -1      0  -1   

   assignee_npo  assignee_ops  postal_code           region  citizen  \
0            -1            -1     398046.0     ЛИПЕЦКАЯ ОБЛ        1   
1            -1            -1          0.0         МОСКВА Г        1   
2            -1            -1     666211.0    ИРКУТСКАЯ ОБЛ       -1   
3            -1            -1     162610.0  ВОЛОГОДСКАЯ ОБЛ        1   
4            -1            -1     427111.0  УДМУРТСКАЯ РЕСП        1   

   fact_addrss  appl_mrkr  evry_qrtr_pmnt  
0            1          0               1  
1            1          0               0  
2            1          0               0  
3            1          0               1  
4            1          0               1

In [120]:
test['year'].value_counts().sort_index()

year
1993      498
1994     1672
1995      340
1996     1771
1997     2669
1998     2079
1999     6396
2000     7030
2001     6922
2002     7797
2003     3865
2004     7559
2005    19239
2006    21805
2007    24651
2008    26469
2009    26093
2010    26397
2011    29345
2012    31057
2013    32758
2014    30751
2015    35197
2016    35660
2017    37097
2018    39271
2019    40265
2020    46102
2021    46745
2022    35921
2023       13
Name: count, dtype: int64

In [5]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 300)

In [6]:
cntrbtrs = pd.read_csv('/content/drive/MyDrive/Hack_Sochi/train/cntrbtrs.csv', sep=';')

In [7]:
cntrbtrs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 911470 entries, 0 to 911469
Data columns (total 3 columns):
 #   Column           Non-Null Count   Dtype  
---  ------           --------------   -----  
 0   slctn_nmbr       911470 non-null  int64  
 1   npo_accnt_id     911470 non-null  object 
 2   accnt_pnsn_schm  911172 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 20.9+ MB


In [ ]:
cntrbtrs.head()

slctn_nmbr                        npo_accnt_id  accnt_pnsn_schm
0           2  0x66FC8B311E1E204187F41966B73E313F              0.0
1           2  0x675F74AFB447EF40AF1E4C042CCA440C              0.0
2           2  0x6FFA52921209184BA47B1E919B713894              0.0
3           2  0xB51B4374207FE0458B29FD1F9CBF69EB              1.0
4           2  0x7AC3935CC4DADE419F8378B9C276DEF7              2.0

In [ ]:
cntrbtrs['slctn_nmbr'].value_counts(dropna=False)

slctn_nmbr
0    432587
3    193013
1    160722
2    125148
Name: count, dtype: int64

In [ ]:
cntrbtrs['accnt_pnsn_schm'].value_counts(dropna=False)

accnt_pnsn_schm
350.0    112539
351.0     98513
354.0     58687
352.0     42615
0.0       36751
          ...  
273.0         1
277.0         1
281.0         1
291.0         1
537.0         1
Name: count, Length: 539, dtype: int64

Всего 4 номера выборки и 538 схем пенс счетов и есть пустой

In [ ]:
cntrbtrs['accnt_pnsn_schm'].value_counts(dropna=False).head(10)

accnt_pnsn_schm
350.0    112539
351.0     98513
354.0     58687
352.0     42615
0.0       36751
430.0     23479
428.0     20597
426.0     18164
427.0     17975
366.0     17909
Name: count, dtype: int64

In [ ]:
cntrbtrs[cntrbtrs['accnt_pnsn_schm'].isna()]

slctn_nmbr                        npo_accnt_id  accnt_pnsn_schm
48137            2  0x80D2005056AB16F911E6B94244A21118              NaN
98139            2  0x80D2005056AB16F911E6B9427B09F913              NaN
101968           2  0x80D2005056AB16F911E6B94CD47B13FA              NaN
105385           2  0x50F03AE3BFCC3E429C71EAD8F872EE0C              NaN
106835           2  0x80D2005056AB16F911E6B94D433AC86D              NaN
...            ...                                 ...              ...
284667           1  0x521B2264D5D1A34C8237B62B6BCD73C1              NaN
285010           1  0x172D33AE68EA8541B3AF1A2CEEBCC2BD              NaN
285034           1  0x97C4B5F299C4DA4CBB2CDC67BCCDEB82              NaN
285086           1  0x8C3459F0572FB04AA874473FC85E53BC              NaN
845823           3  0x9EC49F255267D87541EF821895789A73              NaN

[298 rows x 3 columns]

298 счетов с пустой схемой. Может быть, из 90-х годов ?

In [ ]:
cntrbtrs[cntrbtrs['accnt_pnsn_schm'].isna()]['slctn_nmbr'].value_counts(dropna=False)

slctn_nmbr
1    292
2      5
3      1
Name: count, dtype: int64

Почти все счета с пустой схемой имеют номер выборки 1, при этом выборка 1 только на 3 месте в общем случае. Надо посмотреть отделбно что это за выборка

### train.csv

In [8]:
train = pd.read_csv('/content/drive/MyDrive/Hack_Sochi/train/train.csv')

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3589918 entries, 0 to 3589917
Data columns (total 42 columns):
 #   Column                  Dtype  
---  ------                  -----  
 0   slctn_nmbr              int64  
 1   client_id               object 
 2   npo_account_id          object 
 3   npo_accnts_nmbr         int64  
 4   pmnts_type              int64  
 5   year                    int64  
 6   quarter                 object 
 7   gender                  int64  
 8   age                     int64  
 9   clnt_cprtn_time_d       int64  
 10  actv_prd_d              int64  
 11  lst_pmnt_rcnc_d         int64  
 12  balance                 float64
 13  oprtn_sum_per_qrtr      float64
 14  oprtn_sum_per_year      float64
 15  frst_pmnt_date          object 
 16  lst_pmnt_date_per_qrtr  object 
 17  frst_pmnt               float64
 18  lst_pmnt                float64
 19  pmnts_sum               float64
 20  pmnts_nmbr              int64  
 21  pmnts_sum_per_qrtr      float64

In [ ]:
train.head()

slctn_nmbr                           client_id  \
0           1  0xA095932790098744A2325A8D152C05C7   
1           0  0xF75BAA20A603A2479005DEB80464336E   
2           2  0x0D18081E0556AF4F95A931FBA4159D52   
3           0  0x0AD72BC5475D9A4D83E12350A84F839D   
4           0  0x73DF06339CC25840838408BAD52BE223   

                       npo_account_id  npo_accnts_nmbr  pmnts_type  year  \
0  0xD4DBBAC6561929409BA45725A220613E                1           2  2017   
1  0x3DCFF11974B3D8458CE3569DE9E855D5                2           2  2009   
2  0x9DADF88CB3407C4E89403315F640393E                1           1  2010   
3  0xF59C4E62F115684899EAE9B5D5ECF70F                1           1  2005   
4  0x35BFFA05321C014B9FC29A189E89EDF0                2           2  2007   

  quarter  gender  age  clnt_cprtn_time_d  actv_prd_d  lst_pmnt_rcnc_d  \
0  2017Q4       1   48               8091           0             6757   
1  2009Q1       1   35               3303        1531               34   
2  2010Q1       1   47               1163        1121               34   
3  2005Q4      -1   42                 47           0                0   
4  2007Q4       1   42                876         853               30   

    balance  oprtn_sum_per_qrtr  oprtn_sum_per_year frst_pmnt_date  \
0    679.37               31.34               31.34     1999-07-02   
1  36395.87             1457.59             8037.71     2004-12-31   
2   5569.85              463.41             1953.00     2007-02-20   
3     81.37               81.37               81.37     2005-12-29   
4   6937.65              794.36             3165.98     2005-08-08   

  lst_pmnt_date_per_qrtr  frst_pmnt  lst_pmnt  pmnts_sum  pmnts_nmbr  \
0                    NaN      96.25      0.09      96.25           1   
1             2009-03-11    9823.67    607.40   28402.25          52   
2             2010-03-17     154.47    154.47    5406.50          35   
3             2005-12-29      81.30     81.30      81.30           1   
4             2007-12-09     198.14     26.04    6668.74          26   

   pmnts_sum_per_qrtr  pmnts_sum_per_year  pmnts_nmbr_per_qrtr  \
0               -0.00               -0.00                    0   
1             1457.58             5474.56                    3   
2              463.41             1699.18                    3   
3               81.30               81.30                    1   
4              794.35             3165.97                    3   

   pmnts_nmbr_per_year  incm_sum  incm_per_qrtr  incm_per_year  \
0                    0    583.12          31.34          31.34   
1                   12   7993.61          -0.00        2563.14   
2                   11    163.35          -0.00         253.81   
3                    1      0.06           0.06           0.06   
4                   11    268.91          -0.00          -0.00   

   mgd_accum_period  mgd_payment_period  phone_number  email  lk  \
0               1.8                 1.8             0      0  -1   
1               0.0                 0.0            -1      0  -1   
2               0.1                 0.1            -1     -1  -1   
3               4.0                 4.0            -1      0  -1   
4               0.0                 0.0            -1      0  -1   

   assignee_npo  assignee_ops  postal_code            region  citizen  \
0            -1            -1     446254.0     САМАРСКАЯ ОБЛ       -1   
1            -1            -1     399841.0      ЛИПЕЦКАЯ ОБЛ       -1   
2            -1            -1     302038.0     ОРЛОВСКАЯ ОБЛ        1   
3            -1            -1     620034.0  СВЕРДЛОВСКАЯ ОБЛ        1   
4            -1            -1     398035.0      ЛИПЕЦКАЯ ОБЛ        1   

   fact_addrss  appl_mrkr  evry_qrtr_pmnt  churn  
0           -1          0               0      0  
1            1          0               1      0  
2            1          0               1      0  
3            1          0               1      0  
4            1          0      

Видимо, у нас данные за полный квартал, поэтому признаки именно в этом квартале типа больших выплат должны указывать на отток.

Отток по годам

In [ ]:
train['year'].value_counts().sort_index()

year
1993      3021
1994      9627
1995      2011
1996     10224
1997     15059
1998     11403
1999     37134
2000     39793
2001     39967
2002     44293
2003     21609
2004     42214
2005    108571
2006    122423
2007    139980
2008    149197
2009    147355
2010    147348
2011    168515
2012    174366
2013    185614
2014    174107
2015    200222
2016    202495
2017    210583
2018    222391
2019    230436
2020    261861
2021    262879
2022    205119
2023       101
Name: count, dtype: int64

23 год только 101 запись, в 22 году число записей

In [ ]:
train.groupby(['year'])['churn'].sum()

year
1993       0
1994       0
1995       0
1996       0
1997       0
1998       0
1999       0
2000       0
2001       0
2002       0
2003      19
2004     962
2005    3388
2006    2094
2007    2473
2008    3612
2009    2665
2010    2389
2011    2167
2012    2382
2013    3985
2014    3043
2015    3146
2016    3863
2017    4312
2018    3513
2019    1885
2020    4022
2021    4086
2022    2082
2023       0
Name: churn, dtype: int64

In [ ]:
train.groupby(['year'])['churn'].mean()

year
1993    0.000000
1994    0.000000
1995    0.000000
1996    0.000000
1997    0.000000
1998    0.000000
1999    0.000000
2000    0.000000
2001    0.000000
2002    0.000000
2003    0.000879
2004    0.022789
2005    0.031205
2006    0.017105
2007    0.017667
2008    0.024210
2009    0.018086
2010    0.016213
2011    0.012859
2012    0.013661
2013    0.021469
2014    0.017478
2015    0.015713
2016    0.019077
2017    0.020476
2018    0.015797
2019    0.008180
2020    0.015359
2021    0.015543
2022    0.010150
2023    0.000000
Name: churn, dtype: float64

In [ ]:
19/21609, 962/42214

(0.0008792632699338239, 0.022788648315724643)

In [ ]:
train.head()

slctn_nmbr                           client_id  \
0           1  0xA095932790098744A2325A8D152C05C7   
1           0  0xF75BAA20A603A2479005DEB80464336E   
2           2  0x0D18081E0556AF4F95A931FBA4159D52   
3           0  0x0AD72BC5475D9A4D83E12350A84F839D   
4           0  0x73DF06339CC25840838408BAD52BE223   

                       npo_account_id  npo_accnts_nmbr  pmnts_type  year  \
0  0xD4DBBAC6561929409BA45725A220613E                1           2  2017   
1  0x3DCFF11974B3D8458CE3569DE9E855D5                2           2  2009   
2  0x9DADF88CB3407C4E89403315F640393E                1           1  2010   
3  0xF59C4E62F115684899EAE9B5D5ECF70F                1           1  2005   
4  0x35BFFA05321C014B9FC29A189E89EDF0                2           2  2007   

  quarter  gender  age  clnt_cprtn_time_d  actv_prd_d  lst_pmnt_rcnc_d  \
0  2017Q4       1   48               8091           0             6757   
1  2009Q1       1   35               3303        1531               34   
2  2010Q1       1   47               1163        1121               34   
3  2005Q4      -1   42                 47           0                0   
4  2007Q4       1   42                876         853               30   

    balance  oprtn_sum_per_qrtr  oprtn_sum_per_year frst_pmnt_date  \
0    679.37               31.34               31.34     1999-07-02   
1  36395.87             1457.59             8037.71     2004-12-31   
2   5569.85              463.41             1953.00     2007-02-20   
3     81.37               81.37               81.37     2005-12-29   
4   6937.65              794.36             3165.98     2005-08-08   

  lst_pmnt_date_per_qrtr  frst_pmnt  lst_pmnt  pmnts_sum  pmnts_nmbr  \
0                    NaN      96.25      0.09      96.25           1   
1             2009-03-11    9823.67    607.40   28402.25          52   
2             2010-03-17     154.47    154.47    5406.50          35   
3             2005-12-29      81.30     81.30      81.30           1   
4             2007-12-09     198.14     26.04    6668.74          26   

   pmnts_sum_per_qrtr  pmnts_sum_per_year  pmnts_nmbr_per_qrtr  \
0               -0.00               -0.00                    0   
1             1457.58             5474.56                    3   
2              463.41             1699.18                    3   
3               81.30               81.30                    1   
4              794.35             3165.97                    3   

   pmnts_nmbr_per_year  incm_sum  incm_per_qrtr  incm_per_year  \
0                    0    583.12          31.34          31.34   
1                   12   7993.61          -0.00        2563.14   
2                   11    163.35          -0.00         253.81   
3                    1      0.06           0.06           0.06   
4                   11    268.91          -0.00          -0.00   

   mgd_accum_period  mgd_payment_period  phone_number  email  lk  \
0               1.8                 1.8             0      0  -1   
1               0.0                 0.0            -1      0  -1   
2               0.1                 0.1            -1     -1  -1   
3               4.0                 4.0            -1      0  -1   
4               0.0                 0.0            -1      0  -1   

   assignee_npo  assignee_ops  postal_code            region  citizen  \
0            -1            -1     446254.0     САМАРСКАЯ ОБЛ       -1   
1            -1            -1     399841.0      ЛИПЕЦКАЯ ОБЛ       -1   
2            -1            -1     302038.0     ОРЛОВСКАЯ ОБЛ        1   
3            -1            -1     620034.0  СВЕРДЛОВСКАЯ ОБЛ        1   
4            -1            -1     398035.0      ЛИПЕЦКАЯ ОБЛ        1   

   fact_addrss  appl_mrkr  evry_qrtr_pmnt  churn  
0           -1          0               0      0  
1            1          0               1      0  
2            1          0               1      0  
3            1          0               1      0  
4            1          0      

In [ ]:
train['region'].value_counts().tail(25)

In [ ]:
train['region'].value_counts().head(100)

In [ ]:
train.info()

In [ ]:
train[train['year']>=2004]['region'].value_counts().head(120)

In [10]:
train.head()

slctn_nmbr                           client_id  \
0           1  0xA095932790098744A2325A8D152C05C7   
1           0  0xF75BAA20A603A2479005DEB80464336E   
2           2  0x0D18081E0556AF4F95A931FBA4159D52   
3           0  0x0AD72BC5475D9A4D83E12350A84F839D   
4           0  0x73DF06339CC25840838408BAD52BE223   

                       npo_account_id  npo_accnts_nmbr  pmnts_type  year  \
0  0xD4DBBAC6561929409BA45725A220613E                1           2  2017   
1  0x3DCFF11974B3D8458CE3569DE9E855D5                2           2  2009   
2  0x9DADF88CB3407C4E89403315F640393E                1           1  2010   
3  0xF59C4E62F115684899EAE9B5D5ECF70F                1           1  2005   
4  0x35BFFA05321C014B9FC29A189E89EDF0                2           2  2007   

  quarter  gender  age  clnt_cprtn_time_d  actv_prd_d  lst_pmnt_rcnc_d  \
0  2017Q4       1   48               8091           0             6757   
1  2009Q1       1   35               3303        1531               34   
2  2010Q1       1   47               1163        1121               34   
3  2005Q4      -1   42                 47           0                0   
4  2007Q4       1   42                876         853               30   

    balance  oprtn_sum_per_qrtr  oprtn_sum_per_year frst_pmnt_date  \
0    679.37               31.34               31.34     1999-07-02   
1  36395.87             1457.59             8037.71     2004-12-31   
2   5569.85              463.41             1953.00     2007-02-20   
3     81.37               81.37               81.37     2005-12-29   
4   6937.65              794.36             3165.98     2005-08-08   

  lst_pmnt_date_per_qrtr  frst_pmnt  lst_pmnt  pmnts_sum  pmnts_nmbr  \
0                    NaN      96.25      0.09      96.25           1   
1             2009-03-11    9823.67    607.40   28402.25          52   
2             2010-03-17     154.47    154.47    5406.50          35   
3             2005-12-29      81.30     81.30      81.30           1   
4             2007-12-09     198.14     26.04    6668.74          26   

   pmnts_sum_per_qrtr  pmnts_sum_per_year  pmnts_nmbr_per_qrtr  \
0               -0.00               -0.00                    0   
1             1457.58             5474.56                    3   
2              463.41             1699.18                    3   
3               81.30               81.30                    1   
4              794.35             3165.97                    3   

   pmnts_nmbr_per_year  incm_sum  incm_per_qrtr  incm_per_year  \
0                    0    583.12          31.34          31.34   
1                   12   7993.61          -0.00        2563.14   
2                   11    163.35          -0.00         253.81   
3                    1      0.06           0.06           0.06   
4                   11    268.91          -0.00          -0.00   

   mgd_accum_period  mgd_payment_period  phone_number  email  lk  \
0               1.8                 1.8             0      0  -1   
1               0.0                 0.0            -1      0  -1   
2               0.1                 0.1            -1     -1  -1   
3               4.0                 4.0            -1      0  -1   
4               0.0                 0.0            -1      0  -1   

   assignee_npo  assignee_ops  postal_code            region  citizen  \
0            -1            -1     446254.0     САМАРСКАЯ ОБЛ       -1   
1            -1            -1     399841.0      ЛИПЕЦКАЯ ОБЛ       -1   
2            -1            -1     302038.0     ОРЛОВСКАЯ ОБЛ        1   
3            -1            -1     620034.0  СВЕРДЛОВСКАЯ ОБЛ        1   
4            -1            -1     398035.0      ЛИПЕЦКАЯ ОБЛ        1   

   fact_addrss  appl_mrkr  evry_qrtr_pmnt  churn  
0           -1          0               0      0  
1            1          0               1      0  
2            1          0               1      0  
3            1          0               1      0  
4            1          0      

### Таблица клиентов, склонных к оттоку  
квартал забыл, поэтому были дубли клиентов

In [13]:
train[train['year']==2022]['client_id'].count(), train[train['year']==2022]['client_id'].nunique()

(205119, 65201)

In [14]:
train[train['year']==2022]['npo_accnts_nmbr'].value_counts()

npo_accnts_nmbr
1    126655
2     66057
3      9513
4      2142
5       600
6       126
7        16
8        10
Name: count, dtype: int64

не понимаю, почему уник клиентов не 126655

In [16]:
train[(train['year']==2022)&(train['npo_accnts_nmbr']==2)].head()

slctn_nmbr                           client_id  \
47            0  0xD21813BABB3C5A408485F361B9151CA6   
105           0  0xA62B005056964A2C11EDADE5A9266610   
141           0  0xAB781A088B71F54AA17405F27DF15111   
142           0  0x3EC24DB6A5F97B4B97E19AF1F5728E5A   
156           2  0xDA325E48F9C8AF4294C78682FFC58E36   

                         npo_account_id  npo_accnts_nmbr  pmnts_type  year  \
47   0x8A8E2A8FAEB95E45A3BC64DE56C1A429                2           3  2022   
105  0xA62B005056964A2C11EDAEA5ABE1DCC0                2           1  2022   
141  0xB18F74435EEB4C41ADDA0E73FF52E3BC                2           1  2022   
142  0xA762B17E673CC04092E1F947197F3233                2           3  2022   
156  0xD9B16CDA9122CD4D95297B1405B0217D                2           1  2022   

    quarter  gender  age  clnt_cprtn_time_d  actv_prd_d  lst_pmnt_rcnc_d  \
47   2022Q4       1   45               1095        1006               31   
105  2022Q3       1   26                226         210              147   
141  2022Q3      -1   57               2034        1929               29   
142  2022Q1       1   69               1946        1853               30   
156  2022Q3       1   51               6962        6094               30   

       balance  oprtn_sum_per_qrtr  oprtn_sum_per_year frst_pmnt_date  \
47   284003.20            22230.99           102380.20     2020-03-11   
105    2334.31             2253.01             4562.41     2022-02-16   
141  204276.91             9867.41            34519.78     2017-05-28   
142   78299.76             2714.38            14370.23     2017-02-14   
156   10363.06              487.80             1951.22     2005-12-31   

    lst_pmnt_date_per_qrtr  frst_pmnt  lst_pmnt  pmnts_sum  pmnts_nmbr  \
47              2022-12-12    6246.42   7019.60  275403.55          37   
105             2022-09-14      81.30    762.99    2334.30           4   
141             2022-09-08    2242.26   3050.07  184191.57          77   
142             2022-03-13     915.91   1318.15   69199.49          65   
156             2022-09-07    1971.54    162.60    5223.57          21   

     pmnts_sum_per_qrtr  pmnts_sum_per_year  pmnts_nmbr_per_qrtr  \
47             22230.99           102380.20                    3   
105             2253.00             4562.40                    3   
141             9867.41            34519.78                    5   
142             2714.38            14370.22                    3   
156              487.80             1951.22                    3   

     pmnts_nmbr_per_year  incm_sum  incm_per_qrtr  incm_per_year  \
47                    13   8599.65           -0.0           -0.0   
105                    7     -0.00           -0.0           -0.0   
141                   12  20085.33           -0.0           -0.0   
142                   12   9100.26           -0.0           -0.0   
156                   12   3961.87           -0.0           -0.0   

     mgd_accum_period  mgd_payment_period  phone_number  email  lk  \
47                0.0                 0.0            -1      0   1   
105               0.0                 0.0            -1      0   1   
141               0.0                 0.0            -1      0  -1   
142               0.0                 0.0            -1      0  -1   
156               4.0                 4.0             1     -1  -1   

     assignee_npo  assignee_ops  postal_code  \
47             -1            -1     628011.0   
105            -1            -1          NaN   
141            -1            -1     692900.0   
142            -1            -1     450112.0   
156            -1            -1     162616.0   

                                          region  citizen  fact_addrss  \
47   ХАНТЫ-МАНСИЙСКИЙ АВТОНОМНЫЙ ОКРУГ - ЮГРА АО        1            1   
105                                      КАРЕЛИЯ        1           -1   
141                              ПРИМОРСКИЙ КРАЙ        1            1   
142                                     

In [21]:
train[(train['year']==2022)&(train['client_id']=='0xD21813BABB3C5A408485F361B9151CA6')].sort_values('quarter', ascending=False)

slctn_nmbr                           client_id  \
47                0  0xD21813BABB3C5A408485F361B9151CA6   
1097801           0  0xD21813BABB3C5A408485F361B9151CA6   
803743            0  0xD21813BABB3C5A408485F361B9151CA6   

                             npo_account_id  npo_accnts_nmbr  pmnts_type  \
47       0x8A8E2A8FAEB95E45A3BC64DE56C1A429                2           3   
1097801  0x8A8E2A8FAEB95E45A3BC64DE56C1A429                2           3   
803743   0x8A8E2A8FAEB95E45A3BC64DE56C1A429                2           3   

         year quarter  gender  age  clnt_cprtn_time_d  actv_prd_d  \
47       2022  2022Q4       1   45               1095        1006   
1097801  2022  2022Q3       1   45               1003         914   
803743   2022  2022Q1       1   45                820         733   

         lst_pmnt_rcnc_d    balance  oprtn_sum_per_qrtr  oprtn_sum_per_year  \
47                    31  284003.20            22230.99            102380.2   
1097801               29  261772.21            34900.97            102380.2   
803743                31  200912.91            19289.91            102380.2   

        frst_pmnt_date lst_pmnt_date_per_qrtr  frst_pmnt  lst_pmnt  pmnts_sum  \
47          2020-03-11             2022-12-12    6246.42    7019.6  275403.55   
1097801     2020-03-11             2022-09-11    6246.42    7019.6  253172.56   
803743      2020-03-11             2022-03-14    6246.42    7019.6  192313.26   

         pmnts_nmbr  pmnts_sum_per_qrtr  pmnts_sum_per_year  \
47               37            22230.99            102380.2   
1097801          34            34900.97            102380.2   
803743           27            19289.91            102380.2   

         pmnts_nmbr_per_qrtr  pmnts_nmbr_per_year  incm_sum  incm_per_qrtr  \
47                         3                   13   8599.65           -0.0   
1097801                    4                   13   8599.65           -0.0   
803743                     3                   13   8599.65           -0.0   

         incm_per_year  mgd_accum_period  mgd_payment_period  phone_number  \
47                -0.0               0.0                 0.0            -1   
1097801           -0.0               0.0                 0.0            -1   
803743            -0.0               0.0                 0.0            -1   

         email  lk  assignee_npo  assignee_ops  postal_code  \
47           0   1            -1            -1     628011.0   
1097801      0   1            -1            -1     628011.0   
803743       0   1            -1            -1     628011.0   

                                              region  citizen  fact_addrss  \
47       ХАНТЫ-МАНСИЙСКИЙ АВТОНОМНЫЙ ОКРУГ - ЮГРА АО        1            1   
1097801  ХАНТЫ-МАНСИЙСКИЙ АВТОНОМНЫЙ ОКРУГ - ЮГРА АО        1            1   
803743   ХАНТЫ-МАНСИЙСКИЙ АВТОНОМНЫЙ ОКРУГ - ЮГРА АО        1            1   

         appl_mrkr  evry_qrtr_pmnt  churn  
47               0               1      0  
1097801          0               1      0  
803743           0               1      0

Почему нет 2 квартала, а 1 и 3,4 есть?

In [ ]:
train[(train['client_id']=='0xD21813BABB3C5A408485F361B9151CA6')].sort_values('quarter', ascending=False)

In [ ]:
train[(train['npo_account_id']=='0x8A8E2A8FAEB95E45A3BC64DE56C1A429')].sort_values('quarter', ascending=False).head(10)

### Ладно, это потом, сначала сделать табличку для Эмиля

In [26]:
train[(train['year']==2022)&(train['quarter']=='2022Q4')].head()

slctn_nmbr                           client_id  \
47            0  0xD21813BABB3C5A408485F361B9151CA6   
68            0  0x84FBB407B7082540A2885A2A99D60432   
328           0  0xC5BB7B0D926F6F4387CE8362CC763DC0   
547           0  0xA634005056964A2C11EE4E2718ACBDC8   
832           0  0xB9C2A95250AE0846A0AAA02B8EC5D717   

                         npo_account_id  npo_accnts_nmbr  pmnts_type  year  \
47   0x8A8E2A8FAEB95E45A3BC64DE56C1A429                2           3  2022   
68   0x8C965E174E3E0E4E8C391A0C2E859134                1           3  2022   
328  0xBB42F38143105E4C996968D29BE1008E                2           1  2022   
547  0xA634005056964A2C11EE69ADCBD5BE77                1           3  2022   
832  0x44CA6910C3C5904BA87936C53926BABC                1           3  2022   

    quarter  gender  age  clnt_cprtn_time_d  actv_prd_d  lst_pmnt_rcnc_d  \
47   2022Q4       1   45               1095        1006               31   
68   2022Q4       1   53               1073        1004               33   
328  2022Q4       1   39               2910        2859               30   
547  2022Q4      -1   46                 80          62                0   
832  2022Q4       1   54               2494        2405               30   

       balance  oprtn_sum_per_qrtr  oprtn_sum_per_year frst_pmnt_date  \
47   284003.20            22230.99           102380.20     2020-03-11   
68    95140.92             3180.38            21932.74     2020-03-09   
328  127905.95             2104.41            17695.77     2015-01-12   
547   24039.54            24039.54            24039.54     2022-10-12   
832  650880.74            12109.68            87199.59     2016-05-11   

    lst_pmnt_date_per_qrtr  frst_pmnt  lst_pmnt  pmnts_sum  pmnts_nmbr  \
47              2022-12-12    6246.42   7019.60  275403.55          37   
68              2022-12-08    2346.04   2376.70   91794.52          37   
328             2022-11-10     978.32   1439.78  107774.63          99   
547             2022-12-13    9856.20   6099.61   24039.53           3   
832             2022-12-11    8893.30    250.66  568297.35          80   

     pmnts_sum_per_qrtr  pmnts_sum_per_year  pmnts_nmbr_per_qrtr  \
47             22230.99           102380.20                    3   
68              3180.38            21932.74                    3   
328             2104.41            17695.77                    2   
547            24039.53            24039.53                    3   
832            12109.67            87199.58                    2   

     pmnts_nmbr_per_year  incm_sum  incm_per_qrtr  incm_per_year  \
47                    13   8599.65           -0.0           -0.0   
68                    13   3346.39           -0.0           -0.0   
328                   12  20131.32           -0.0           -0.0   
547                    3     -0.00           -0.0           -0.0   
832                   11  82583.36           -0.0           -0.0   

     mgd_accum_period  mgd_payment_period  phone_number  email  lk  \
47                0.0                 0.0            -1      0   1   
68                0.0                 0.0            -1      0  -1   
328               0.0                 0.0            -1      0   1   
547               0.0                 0.0            -1      0  -1   
832               0.0                 0.0            -1      0  -1   

     assignee_npo  assignee_ops  postal_code  \
47             -1            -1     628011.0   
68             -1            -1     446200.0   
328            -1            -1     427990.0   
547            -1            -1     629831.0   
832            -1            -1     614016.0   

                                          region  citizen  fact_addrss  \
47   ХАНТЫ-МАНСИЙСКИЙ АВТОНОМНЫЙ ОКРУГ - ЮГРА АО        1            1   
68                                 САМАРСКАЯ ОБЛ        1            1   
328                              УДМУРТСКАЯ РЕСП       -1            1   
547                            ЯМАЛО-НЕН

In [27]:
train[(train['year']==2022)&(train['quarter']=='2022Q4')]['client_id'].count(), train[(train['year']==2022)&(train['quarter']=='2022Q4')]['client_id'].nunique()

(53121, 52324)

In [28]:
train[(train['year']==2022)&(train['quarter']=='2022Q4')]['npo_accnts_nmbr'].value_counts()

npo_accnts_nmbr
1    32803
2    16820
3     2565
4      723
5      166
6       36
7        5
8        3
Name: count, dtype: int64

In [37]:
32803+16820*2+2565*33+723*4+166*5+36*6

155026

Вывод: не все договоры показаны, видимо


In [39]:
columns_2front = ['client_id', 'npo_account_id', 'gender', 'age', 'region', 'npo_accnts_nmbr', 'pmnts_type','balance','lst_pmnt_date_per_qrtr',
                  'phone_number','email','lk']

In [ ]:
train.columns

In [41]:
tr_fron1 = train[(train['year']==2022)&(train['quarter']=='2022Q4')][columns_2front]

In [55]:
tr_fron1.head()

client_id                      npo_account_id  \
47   0xD21813BABB3C5A408485F361B9151CA6  0x8A8E2A8FAEB95E45A3BC64DE56C1A429   
68   0x84FBB407B7082540A2885A2A99D60432  0x8C965E174E3E0E4E8C391A0C2E859134   
328  0xC5BB7B0D926F6F4387CE8362CC763DC0  0xBB42F38143105E4C996968D29BE1008E   
547  0xA634005056964A2C11EE4E2718ACBDC8  0xA634005056964A2C11EE69ADCBD5BE77   
832  0xB9C2A95250AE0846A0AAA02B8EC5D717  0x44CA6910C3C5904BA87936C53926BABC   

    gender  age                                       region  npo_accnts_nmbr  \
47       М   45  ХАНТЫ-МАНСИЙСКИЙ АВТОНОМНЫЙ ОКРУГ - ЮГРА АО                2   
68       М   53                                САМАРСКАЯ ОБЛ                1   
328      М   39                              УДМУРТСКАЯ РЕСП                2   
547      Ж   46                            ЯМАЛО-НЕНЕЦКИЙ АО                1   
832      М   54                                ПЕРМСКИЙ КРАЙ                1   

          pmnts_type    balance lst_pmnt_date_per_qrtr phone_number  \
47   от работодателя  284003.20             2022-12-12          Нет   
68   от работодателя   95140.92             2022-12-08          Нет   
328        смешанные  127905.95             2022-11-10          Нет   
547  от работодателя   24039.54             2022-12-13          Нет   
832  от работодателя  650880.74             2022-12-11          Нет   

          email   lk  
47   Нет данных   Да  
68   Нет данных  Нет  
328  Нет данных   Да  
547  Нет данных  Нет  
832  Нет данных  Нет

In [44]:
tr_fron1['gender'] = tr_fron1['gender'].map({-1:'Ж', 1:'М'})

In [ ]:
tr_fron1['phone_number'] = tr_fron1['phone_number'].map({1:'Да', -1:'Нет', 0:'Нет данных'})

In [50]:
tr_fron1['email'] = tr_fron1['email'].map({1:'Да', -1:'Нет', 0:'Нет данных'})

In [52]:
tr_fron1['lk'] = tr_fron1['lk'].map({1:'Да', -1:'Нет', 0:'Нет данных'})

In [54]:
tr_fron1['pmnts_type'] = tr_fron1['pmnts_type'].map({0:'не определен', 1:'смешанные', 2:'через банк', 3:'от работодателя'})

In [61]:
tr_fron1['churn_prop'] = 1

In [64]:
tr_fron1['churn_prop'] = tr_fron1['churn_prop'].apply(lambda x: round(np.random.uniform(0, 1),4))

In [ ]:
#tr_fron1['perc_rank_churn'] = df.Pay.rank(pct = True)

In [67]:
tr_fron1.columns

Index(['client_id', 'npo_account_id', 'gender', 'age', 'region',
       'npo_accnts_nmbr', 'pmnts_type', 'balance', 'lst_pmnt_date_per_qrtr',
       'phone_number', 'email', 'lk', 'churn_prop'],
      dtype='object')

In [68]:
tr_fron1[['client_id', 'npo_account_id','churn_prop', 'gender', 'age', 'region',
       'npo_accnts_nmbr', 'pmnts_type', 'balance', 'lst_pmnt_date_per_qrtr',
       'phone_number', 'email', 'lk']].head()

client_id                      npo_account_id  \
47   0xD21813BABB3C5A408485F361B9151CA6  0x8A8E2A8FAEB95E45A3BC64DE56C1A429   
68   0x84FBB407B7082540A2885A2A99D60432  0x8C965E174E3E0E4E8C391A0C2E859134   
328  0xC5BB7B0D926F6F4387CE8362CC763DC0  0xBB42F38143105E4C996968D29BE1008E   
547  0xA634005056964A2C11EE4E2718ACBDC8  0xA634005056964A2C11EE69ADCBD5BE77   
832  0xB9C2A95250AE0846A0AAA02B8EC5D717  0x44CA6910C3C5904BA87936C53926BABC   

     churn_prop gender  age                                       region  \
47       0.8149      М   45  ХАНТЫ-МАНСИЙСКИЙ АВТОНОМНЫЙ ОКРУГ - ЮГРА АО   
68       0.2625      М   53                                САМАРСКАЯ ОБЛ   
328      0.3557      М   39                              УДМУРТСКАЯ РЕСП   
547      0.3990      Ж   46                            ЯМАЛО-НЕНЕЦКИЙ АО   
832      0.9250      М   54                                ПЕРМСКИЙ КРАЙ   

     npo_accnts_nmbr       pmnts_type    balance lst_pmnt_date_per_qrtr  \
47                 2  от работодателя  284003.20             2022-12-12   
68                 1  от работодателя   95140.92             2022-12-08   
328                2        смешанные  127905.95             2022-11-10   
547                1  от работодателя   24039.54             2022-12-13   
832                1  от работодателя  650880.74             2022-12-11   

    phone_number       email   lk  
47           Нет  Нет данных   Да  
68           Нет  Нет данных  Нет  
328          Нет  Нет данных   Да  
547          Нет  Нет данных  Нет  
832          Нет  Нет данных  Нет

### Сохраняю


In [73]:
tr_fron1[['client_id', 'npo_account_id','churn_prop', 'gender', 'age', 'region',
       'npo_accnts_nmbr', 'pmnts_type', 'balance', 'lst_pmnt_date_per_qrtr',
       'phone_number', 'email', 'lk']].to_csv('/content/drive/MyDrive/Hack_Sochi/acc_churn_t1.csv', index = False)

In [9]:
acc1 = pd.read_csv('/content/drive/MyDrive/Hack_Sochi/acc_churn_t1.csv')

In [12]:
acc1['lk'].value_counts()

lk
Да     27247
Нет    25874
Name: count, dtype: int64

In [10]:
acc1['phone_number'].value_counts()

phone_number
Нет           48923
Нет данных     4050
Да              148
Name: count, dtype: int64

In [11]:
acc1['email'].value_counts()

email
Нет данных    48640
Нет            4465
Да               16
Name: count, dtype: int64

Таблица транзакций

In [83]:
transact = pd.read_csv('/content/drive/MyDrive/Hack_Sochi/train/trnsctns.csv', sep=';')

In [84]:
transact.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26337901 entries, 0 to 26337900
Data columns (total 7 columns):
 #   Column          Dtype  
---  ------          -----  
 0   slctn_nmbr      int64  
 1   npo_account_id  object 
 2   npo_sum         float64
 3   npo_oprtn_date  object 
 4   npo_oprtn_grp   int64  
 5   quarter         object 
 6   year            int64  
dtypes: float64(1), int64(3), object(3)
memory usage: 1.4+ GB


In [87]:
transact.head()

slctn_nmbr                      npo_account_id  npo_sum npo_oprtn_date  \
0           2  0x555990CC98CCF8469BE5911D37811A4A    57.72     2000-01-02   
1           2  0x555990CC98CCF8469BE5911D37811A4A   288.61     2000-01-03   
2           2  0x555990CC98CCF8469BE5911D37811A4A    78.04     2000-01-16   
3           2  0x555990CC98CCF8469BE5911D37811A4A    78.04     2000-02-15   
4           2  0x555990CC98CCF8469BE5911D37811A4A    85.36     2000-03-16   

   npo_oprtn_grp quarter  year  
0              0  2000Q1  2000  
1              0  2000Q1  2000  
2              1  2000Q1  2000  
3              1  2000Q1  2000  
4              1  2000Q1  2000

In [89]:
transact.groupby('slctn_nmbr').agg({'quarter':['min', 'max']})

quarter        
               min     max
slctn_nmbr                
0           1999Q4  2023Q1
1           1993Q2  2023Q1
2           2000Q1  2023Q1
3           2003Q3  2023Q1

In [85]:
transact['year'].value_counts().sort_index()

year
1993      17294
1994      55367
1995      15922
1996      62025
1997      66161
1998      51707
1999      93904
2000      95199
2001     111330
2002     102087
2003      50516
2004     317296
2005     648101
2006    1041523
2007    1015132
2008    1759620
2009    1445688
2010    1468312
2011    1182721
2012    2087359
2013    1741909
2014    1490955
2015     926927
2016    2042050
2017    1399632
2018    1656100
2019     935440
2020    2009646
2021    1429794
2022     936185
2023      81999
Name: count, dtype: int64

In [86]:
transact_2 = transact[transact['year'].between(2019, 2022)]

In [ ]:
train.head()

In [93]:
train.groupby('slctn_nmbr').agg({'quarter':['min', 'max']})

quarter        
               min     max
slctn_nmbr                
0           2003Q4  2023Q1
1           1993Q2  2023Q1
2           2001Q3  2023Q1
3           2005Q4  2023Q1

In [100]:
train[(train['churn']==1)&(train['quarter'].between('2019','2022Q4'))].head()

slctn_nmbr                           client_id  \
38            0  0x04F305A6C59E984FAB50F1CCF18E0496   
125           0  0x2973C561A47AB04097020E2F92A73730   
211           0  0xC423AAF753329942930C200D46A60F63   
219           0  0xFE8CBBCA10FA554F985122B1B9DE18CC   
470           2  0xA385D2406E8E2F4092A05471D41552B9   

                         npo_account_id  npo_accnts_nmbr  pmnts_type  year  \
38   0x17AA4D9556DBC64DA3D6BD7F1C1B9F0C                1           1  2020   
125  0x99F0F6D8D97839478D35FD901D38ECBB                1           1  2021   
211  0xADBBCA8A39660049B9AA58143FE121FC                2           3  2021   
219  0x411584FCF08931438FB171F4C26CC936                2           3  2021   
470  0x5A4A8C2247731F449A8686590B40019A                1           1  2021   

    quarter  gender  age  clnt_cprtn_time_d  actv_prd_d  lst_pmnt_rcnc_d  \
38   2020Q4       1   43               2733        2465              268   
125  2021Q4      -1   53               1961        1888               30   
211  2021Q1       1   42                598         583               36   
219  2021Q3      -1   47               1260        1221               28   
470  2021Q3       1   61               7269        5729               30   

       balance  oprtn_sum_per_qrtr  oprtn_sum_per_year frst_pmnt_date  \
38     4645.80             4645.81          -291026.40     2013-07-08   
125   68925.82             5627.43            16547.84     2016-10-12   
211  209349.92          -169424.70          -187195.19     2019-08-11   
219   72498.85             8052.72           -53737.46     2018-05-07   
470  343594.03             2439.02          -336276.96     2005-12-31   

    lst_pmnt_date_per_qrtr  frst_pmnt  lst_pmnt  pmnts_sum  pmnts_nmbr  \
38                     NaN    1614.86   3278.11  249740.47          83   
125             2021-12-13     442.27   1009.23   60080.03          69   
211             2021-03-16     813.00  13442.63  218145.02          20   
219             2021-09-09    1278.78   2528.74   68890.96          45   
470             2021-09-07   39837.39    813.00  193089.43         190   

     pmnts_sum_per_qrtr  pmnts_sum_per_year  pmnts_nmbr_per_qrtr  \
38                -0.00            12140.88                    0   
125             2393.00            13313.40                    3   
211            35597.36            35597.36                    3   
219             8052.72            22951.65                    4   
470             2439.02             7317.07                    3   

     pmnts_nmbr_per_year   incm_sum  incm_per_qrtr  incm_per_year  \
38                     4   62718.42        4645.81        4645.81   
125                   14    8845.78        3234.43        3234.43   
211                    3    4647.52          -0.00          -0.00   
219                   12    3607.88          -0.00          -0.00   
470                    9  129656.20          -0.00          -0.00   

     mgd_accum_period  mgd_payment_period  phone_number  email  lk  \
38                0.0                 0.0            -1      0   1   
125               0.0                 0.0            -1      0   1   
211               0.0                 0.0            -1      0   1   
219               0.0                 0.0            -1      0   1   
470               4.0                 4.0            -1     -1  -1   

     assignee_npo  assignee_ops  postal_code  \
38             -1            -1     628462.0   
125            -1            -1     452613.0   
211            -1            -1     660021.0   
219            -1            -1     352800.0   
470            -1            -1     162612.0   

                                          region  citizen  fact_addrss  \
38   ХАНТЫ-МАНСИЙСКИЙ АВТОНОМНЫЙ ОКРУГ - ЮГРА АО        1            1   
125                            БАШКОРТОСТАН РЕСП        1            1   
211                            КРАСНОЯРСКИЙ КРАЙ        1            1   
219                           КРАС

In [ ]:
tr1922 = train[(train['churn']==1)&(train['quarter'].between('2019','2022Q4'))][]

In [101]:
train.columns

Index(['slctn_nmbr', 'client_id', 'npo_account_id', 'npo_accnts_nmbr',
       'pmnts_type', 'year', 'quarter', 'gender', 'age', 'clnt_cprtn_time_d',
       'actv_prd_d', 'lst_pmnt_rcnc_d', 'balance', 'oprtn_sum_per_qrtr',
       'oprtn_sum_per_year', 'frst_pmnt_date', 'lst_pmnt_date_per_qrtr',
       'frst_pmnt', 'lst_pmnt', 'pmnts_sum', 'pmnts_nmbr',
       'pmnts_sum_per_qrtr', 'pmnts_sum_per_year', 'pmnts_nmbr_per_qrtr',
       'pmnts_nmbr_per_year', 'incm_sum', 'incm_per_qrtr', 'incm_per_year',
       'mgd_accum_period', 'mgd_payment_period', 'phone_number', 'email', 'lk',
       'assignee_npo', 'assignee_ops', 'postal_code', 'region', 'citizen',
       'fact_addrss', 'appl_mrkr', 'evry_qrtr_pmnt', 'churn'],
      dtype='object')

### Я хочу сделать поквартально сумму потерь по ушедшим договорам  
Но вопрос - если брать balance, не будет ли там 0, если клиент ушел?

In [13]:
train[(train['churn']==1)&(train['quarter'].between('2019','2022Q4'))].head()

slctn_nmbr                           client_id  \
38            0  0x04F305A6C59E984FAB50F1CCF18E0496   
125           0  0x2973C561A47AB04097020E2F92A73730   
211           0  0xC423AAF753329942930C200D46A60F63   
219           0  0xFE8CBBCA10FA554F985122B1B9DE18CC   
470           2  0xA385D2406E8E2F4092A05471D41552B9   

                         npo_account_id  npo_accnts_nmbr  pmnts_type  year  \
38   0x17AA4D9556DBC64DA3D6BD7F1C1B9F0C                1           1  2020   
125  0x99F0F6D8D97839478D35FD901D38ECBB                1           1  2021   
211  0xADBBCA8A39660049B9AA58143FE121FC                2           3  2021   
219  0x411584FCF08931438FB171F4C26CC936                2           3  2021   
470  0x5A4A8C2247731F449A8686590B40019A                1           1  2021   

    quarter  gender  age  clnt_cprtn_time_d  actv_prd_d  lst_pmnt_rcnc_d  \
38   2020Q4       1   43               2733        2465              268   
125  2021Q4      -1   53               1961        1888               30   
211  2021Q1       1   42                598         583               36   
219  2021Q3      -1   47               1260        1221               28   
470  2021Q3       1   61               7269        5729               30   

       balance  oprtn_sum_per_qrtr  oprtn_sum_per_year frst_pmnt_date  \
38     4645.80             4645.81          -291026.40     2013-07-08   
125   68925.82             5627.43            16547.84     2016-10-12   
211  209349.92          -169424.70          -187195.19     2019-08-11   
219   72498.85             8052.72           -53737.46     2018-05-07   
470  343594.03             2439.02          -336276.96     2005-12-31   

    lst_pmnt_date_per_qrtr  frst_pmnt  lst_pmnt  pmnts_sum  pmnts_nmbr  \
38                     NaN    1614.86   3278.11  249740.47          83   
125             2021-12-13     442.27   1009.23   60080.03          69   
211             2021-03-16     813.00  13442.63  218145.02          20   
219             2021-09-09    1278.78   2528.74   68890.96          45   
470             2021-09-07   39837.39    813.00  193089.43         190   

     pmnts_sum_per_qrtr  pmnts_sum_per_year  pmnts_nmbr_per_qrtr  \
38                -0.00            12140.88                    0   
125             2393.00            13313.40                    3   
211            35597.36            35597.36                    3   
219             8052.72            22951.65                    4   
470             2439.02             7317.07                    3   

     pmnts_nmbr_per_year   incm_sum  incm_per_qrtr  incm_per_year  \
38                     4   62718.42        4645.81        4645.81   
125                   14    8845.78        3234.43        3234.43   
211                    3    4647.52          -0.00          -0.00   
219                   12    3607.88          -0.00          -0.00   
470                    9  129656.20          -0.00          -0.00   

     mgd_accum_period  mgd_payment_period  phone_number  email  lk  \
38                0.0                 0.0            -1      0   1   
125               0.0                 0.0            -1      0   1   
211               0.0                 0.0            -1      0   1   
219               0.0                 0.0            -1      0   1   
470               4.0                 4.0            -1     -1  -1   

     assignee_npo  assignee_ops  postal_code  \
38             -1            -1     628462.0   
125            -1            -1     452613.0   
211            -1            -1     660021.0   
219            -1            -1     352800.0   
470            -1            -1     162612.0   

                                          region  citizen  fact_addrss  \
38   ХАНТЫ-МАНСИЙСКИЙ АВТОНОМНЫЙ ОКРУГ - ЮГРА АО        1            1   
125                            БАШКОРТОСТАН РЕСП        1            1   
211                            КРАСНОЯРСКИЙ КРАЙ        1            1   
219                           КРАС

### Колоссальный пример с дата ликом

In [15]:
train[(train['npo_account_id']=='0x17AA4D9556DBC64DA3D6BD7F1C1B9F0C')&(train['quarter'].between('2019','2022Q4'))].sort_values('quarter')

slctn_nmbr                           client_id  \
1259753           0  0x04F305A6C59E984FAB50F1CCF18E0496   
1153688           0  0x04F305A6C59E984FAB50F1CCF18E0496   
2653077           0  0x04F305A6C59E984FAB50F1CCF18E0496   
980312            0  0x04F305A6C59E984FAB50F1CCF18E0496   
642738            0  0x04F305A6C59E984FAB50F1CCF18E0496   
38                0  0x04F305A6C59E984FAB50F1CCF18E0496   

                             npo_account_id  npo_accnts_nmbr  pmnts_type  \
1259753  0x17AA4D9556DBC64DA3D6BD7F1C1B9F0C                1           1   
1153688  0x17AA4D9556DBC64DA3D6BD7F1C1B9F0C                1           1   
2653077  0x17AA4D9556DBC64DA3D6BD7F1C1B9F0C                1           1   
980312   0x17AA4D9556DBC64DA3D6BD7F1C1B9F0C                1           1   
642738   0x17AA4D9556DBC64DA3D6BD7F1C1B9F0C                1           1   
38       0x17AA4D9556DBC64DA3D6BD7F1C1B9F0C                1           1   

         year quarter  gender  age  clnt_cprtn_time_d  actv_prd_d  \
1259753  2019  2019Q1       1   42               2093        2068   
1153688  2019  2019Q2       1   42               2184        2164   
2653077  2019  2019Q4       1   42               2368        2316   
980312   2020  2020Q1       1   43               2458        2437   
642738   2020  2020Q2       1   43               2549        2465   
38       2020  2020Q4       1   43               2733        2465   

         lst_pmnt_rcnc_d    balance  oprtn_sum_per_qrtr  oprtn_sum_per_year  \
1259753               36  244826.42            12409.63            63255.41   
1153688               31  263085.04            18258.62            63255.41   
2653077               29  295672.18            25168.03            63255.41   
980312                64  304534.96             8862.77          -291026.40   
642738                28  307813.08          -304534.96          -291026.40   
38                   268    4645.80             4645.81          -291026.40   

        frst_pmnt_date lst_pmnt_date_per_qrtr  frst_pmnt  lst_pmnt  pmnts_sum  \
1259753     2013-07-08             2019-03-07    1614.86   3278.11  202902.96   
1153688     2013-07-08             2019-06-11    1614.86   3278.11  221161.58   
2653077     2013-07-08             2019-11-10    1614.86   3278.11  237599.56   
980312      2013-07-08             2020-03-10    1614.86   3278.11  246462.34   
642738      2013-07-08             2020-04-07    1614.86   3278.11  249740.47   
38          2013-07-08                    NaN    1614.86   3278.11  249740.47   

         pmnts_nmbr  pmnts_sum_per_qrtr  pmnts_sum_per_year  \
1259753          70            12409.63            47106.25   
1153688          74            18258.61            47106.25   
2653077          79             9018.87            47106.25   
980312           82             8862.77            12140.88   
642738           83             3278.11            12140.88   
38               83               -0.00            12140.88   

         pmnts_nmbr_per_qrtr  pmnts_nmbr_per_year  incm_sum  incm_per_qrtr  \
1259753                    3                   12  41923.45          -0.00   
1153688                    4                   12  41923.45          -0.00   
2653077                    2                   12  58072.61       16149.15   
980312                     3                    4  58072.61          -0.00   
642738                     1                    4  58072.61          -0.00   
38                         0                    4  62718.42        4645.81   

         incm_per_year  mgd_accum_period  mgd_payment_period  phone_number  \
1259753       16149.15               0.0                 0.0            -1   
1153688       16149.15               0.0                 0.0            -1   
2653077       16149.15               0.0                 0.0            -1   
980312         4645.81               0.0                 0.0            -1   
642738         4645.81               0.0                 0.0            -1   

In [16]:
train[(train['npo_account_id']=='0x99F0F6D8D97839478D35FD901D38ECBB')&(train['quarter'].between('2019','2022Q4'))].sort_values('quarter')

slctn_nmbr                           client_id  \
1092163           0  0x2973C561A47AB04097020E2F92A73730   
377625            0  0x2973C561A47AB04097020E2F92A73730   
2942659           0  0x2973C561A47AB04097020E2F92A73730   
2964705           0  0x2973C561A47AB04097020E2F92A73730   
3424539           0  0x2973C561A47AB04097020E2F92A73730   
1076465           0  0x2973C561A47AB04097020E2F92A73730   
2845367           0  0x2973C561A47AB04097020E2F92A73730   
3563643           0  0x2973C561A47AB04097020E2F92A73730   
22147             0  0x2973C561A47AB04097020E2F92A73730   
125               0  0x2973C561A47AB04097020E2F92A73730   

                             npo_account_id  npo_accnts_nmbr  pmnts_type  \
1092163  0x99F0F6D8D97839478D35FD901D38ECBB                1           1   
377625   0x99F0F6D8D97839478D35FD901D38ECBB                1           1   
2942659  0x99F0F6D8D97839478D35FD901D38ECBB                1           1   
2964705  0x99F0F6D8D97839478D35FD901D38ECBB                1           1   
3424539  0x99F0F6D8D97839478D35FD901D38ECBB                1           1   
1076465  0x99F0F6D8D97839478D35FD901D38ECBB                1           1   
2845367  0x99F0F6D8D97839478D35FD901D38ECBB                1           1   
3563643  0x99F0F6D8D97839478D35FD901D38ECBB                1           1   
22147    0x99F0F6D8D97839478D35FD901D38ECBB                1           1   
125      0x99F0F6D8D97839478D35FD901D38ECBB                1           1   

         year quarter  gender  age  clnt_cprtn_time_d  actv_prd_d  \
1092163  2019  2019Q2      -1   51               1047         972   
377625   2019  2019Q3      -1   51               1139        1065   
2942659  2019  2019Q4      -1   51               1231        1156   
2964705  2020  2020Q1      -1   52               1321        1246   
3424539  2020  2020Q2      -1   52               1412        1351   
1076465  2020  2020Q3      -1   52               1504        1432   
2845367  2020  2020Q4      -1   52               1596        1523   
3563643  2021  2021Q1      -1   53               1686        1611   
22147    2021  2021Q2      -1   53               1777        1702   
125      2021  2021Q4      -1   53               1961        1888   

         lst_pmnt_rcnc_d   balance  oprtn_sum_per_qrtr  oprtn_sum_per_year  \
1092163               32  30031.19             2827.80            13530.14   
377625                33  33894.79             3863.60            13530.14   
2942659               32  38047.55             4152.76            13530.14   
2964705               34  40847.86             2800.32            14330.44   
3424539               33  44253.22             3405.36            14330.44   
1076465               19  48329.56             4076.34            14330.44   
2845367               30  52377.98             4048.42            14330.44   
3563643               31  55253.79             2875.80            16547.84   
22147                 33  58281.66             3027.87            16547.84   
125                   30  68925.82             5627.43            16547.84   

        frst_pmnt_date lst_pmnt_date_per_qrtr  frst_pmnt  lst_pmnt  pmnts_sum  \
1092163     2016-10-12             2019-06-11     442.27   1009.23   28088.54   
377625      2016-10-12             2019-09-12     442.27   1009.23   31952.14   
2942659     2016-10-12             2019-12-12     442.27   1009.23   34211.29   
2964705     2016-10-12             2020-03-11     442.27   1009.23   37011.61   
3424539     2016-10-12             2020-06-24     442.27   1009.23   40416.96   
1076465     2016-10-12             2020-09-13     442.27   1009.23   44493.30   
2845367     2016-10-12             2020-12-13     442.27   1009.23   46766.62   
3563643     2016-10-12             2021-03-11     442.27   1009.23   49642.43   
22147       2016-10-12             2021-06-10     442.27   1009.23   52670.30   
125         2016-10-12             2021-12-13     442.27   1009.23   60080.03   

         pm

## Делаю таблицу для расчета суммы потерь по региону-кварталам  
Топ регионов беру и все

In [ ]:
train[(train['churn']==1)&(train['quarter'].between('2018','2022Q4'))]['region'].value_counts()

Почему на 1 месте по оттоку Вологодская обл и Югра?  
Вологодская, Башкортостан, Липецкая, Югра - больше всего записей

In [93]:
a = train[(train['quarter'].between('2018','2022Q4'))& (~train['region'].isin(['БЕЛАРУСЬ','КАЗАХСТАН','УКРАИНА','ОБЪЕДИНЕННЫЕ АРАБСКИЕ ЭМИРАТЫ']))]

In [94]:
a['region'] = a['region'].replace(['БАШКОРТОСТАН РЕСП.',  'БАШКОРТОСТАН',  'БАШКОРТОСТАН РЕСП',  'РЕСП БАШКОРТОСТАН','БЕЛЕБЕЕВСКИЙ','БЕЛЕБЕЕВСКИЙ Р-Н'
  ,'ДЮРТЮЛИНСКИЙ','ДЮРТЮЛИНСКИЙ Р-Н','ИШИМБАЙСКИЙ','КРАСНОКАМСКИЙ','ТУЙМАЗИНСКИЙ','ТУЙМАЗИНСКИЙ Р-Н','УФИМСКИЙ','ЯНАУЛЬСКИЙ','БИРСКИЙ'
  ,'ЯНАУЛЬСКИЙ Р-Н','ЧИШМИНСКИЙ','ТАТЫШЛИНСКИЙ','УФИМСКИЙ Р-Н','УЧАЛИНСКИЙ','БАЙМАКСКИЙ','БАКАЛИНСКИЙ','ГАФУРИЙСКИЙ','ДАВЛЕКАНОВСКИЙ'
  ,'ЕРМЕКЕЕВСКИЙ','ИГЛИНСКИЙ','ИШИМБАЙСКИЙ Р-Н','КАЛТАСИНСКИЙ','КРАСНОКАМСКИЙ Р-Н','КУШНАРЕНКОВСКИЙ','ШАРАНСКИЙ','МЕЛЕУЗОВСКИЙ','КУГАРЧИНСКИЙ'
  ,'КАРАИДЕЛЬСКИЙ','КАЛТАСИНСКИЙ Р-Н','БЛАГОВЕЩЕНСКИЙ','НУРИМАНОВСКИЙ','ЗИАНЧУРИНСКИЙ'], 'БАШКОРТОСТАН РЕСП.')

<ipython-input-94-33111bf3221c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['region'] = a['region'].replace(['БАШКОРТОСТАН РЕСП.',  'БАШКОРТОСТАН',  'БАШКОРТОСТАН РЕСП',  'РЕСП БАШКОРТОСТАН','БЕЛЕБЕЕВСКИЙ','БЕЛЕБЕЕВСКИЙ Р-Н'


In [ ]:
a['region'] = a['region'].replace(['ХАНТЫ-МАНСИЙСКИЙ АВТОНОМНЫЙ ОКРУГ - ЮГРА','ХАНТЫ-МАНСИЙСКИЙ АВТОНОМНЫЙ ОКРУГ - ЮГРА АО','ХАНТЫ-МАНСИЙСКИЙ АВТОНОМНЫЙ ОКРУГ - ЮГРА АО.',
                                   'ХАНТЫ-МАНСИЙСКИЙ АО','ХАНТЫ-МАНСИЙСКИЙ-ЮГРА АО','НЕФТЕЮГАНСКИЙ Р-Н'], 'ХАНТЫ-МАНСИЙСКИЙ АО - ЮГРА')
a['region'] = a['region'].replace(['ИРКУТСКАЯ','ИРКУТСКАЯ ОБЛ'], 'ИРКУТСКАЯ ОБЛ')
a['region'] = a['region'].replace(['КЕМЕРОВСКАЯ ОБЛ','КЕМЕРОВСКАЯ ОБЛАСТЬ - КУЗБАСС','КЕМЕРОВСКАЯ ОБЛАСТЬ - КУЗБАСС ОБЛ'], 'КЕМЕРОВСКАЯ ОБЛ')
a['region'] = a['region'].replace(['КРАСНОДАРСКИЙ','КРАСНОДАРСКИЙ КРАЙ','КРАСНОДАРСКИЙ КРАЙ.'], 'КРАСНОДАРСКИЙ КРАЙ')
a['region'] = a['region'].replace(['КРАСНОЯРСКИЙ КРАЙ','КРАСНОЯРСКИЙ','КРАСНОЯРСКИЙ КРАЙ.'], 'КРАСНОЯРСКИЙ КРАЙ')
a['region'] = a['region'].replace(['ОРЕНБУРГСКАЯ','ОРЕНБУРГСКАЯ ОБЛ'], 'ОРЕНБУРГСКАЯ ОБЛ')
a['region'] = a['region'].replace(['САМАРСКАЯ','САМАРСКАЯ ОБЛ','САМАРСКАЯ ОБЛ.'], 'САМАРСКАЯ ОБЛ')
a['region'] = a['region'].replace(['ЯМАЛО-НЕНЕЦКИЙ','ЯМАЛО-НЕНЕЦКИЙ АО','ЯМАЛО-НЕНЕЦКИЙ АО.','ЯМАЛО-НЕНЕЦКИЙ АВТОНОМНЫЙ ОКРУГ'], 'ЯМАЛО-НЕНЕЦКИЙ АО')
a['region'] = a['region'].replace(['ЧЕЧЕНСКАЯ','ЧЕЧЕНСКАЯ РЕСП'], 'ЧЕЧЕНСКАЯ РЕСП')
a['region'] = a['region'].replace(['ХАБАРОВСКИЙ','ХАБАРОВСКИЙ КРАЙ'], 'ХАБАРОВСКИЙ КРАЙ')
a['region'] = a['region'].replace(['ТЮМЕНСКАЯ','ТЮМЕНСКАЯ ОБЛ'], 'ТЮМЕНСКАЯ ОБЛ')
a['region'] = a['region'].replace(['УДМУРТСКАЯ','УДМУРТСКАЯ РЕСП'], 'УДМУРТСКАЯ РЕСП')
a['region'] = a['region'].replace(['МОСКВА','МОСКВА Г','МОСКВА Г.'], 'МОСКВА')
a['region'] = a['region'].replace(['ЛИПЕЦКАЯ','ЛИПЕЦКАЯ ОБЛ','ЛИПЕЦКАЯ ОБЛ.'], 'ЛИПЕЦКАЯ ОБЛ')
a['region'] = a['region'].replace(['РЯЗАНСКАЯ','РЯЗАНСКАЯ ОБЛ','РЯЗАНСКАЯ ОБЛ.'], 'РЯЗАНСКАЯ ОБЛ')
a['region'] = a['region'].replace(['ТЮМЕНСКАЯ','ТЮМЕНСКАЯ ОБЛ','ТЮМЕНСКАЯ ОБЛ.'], 'ТЮМЕНСКАЯ ОБЛ')
a['region'] = a['region'].replace(['КОМИ','КОМИ РЕСП','КОМИ РЕСП.'], 'КОМИ РЕСП')
a['region'] = a['region'].replace(['ИРКУТСКАЯ','ИРКУТСКАЯ ОБЛ','ИРКУТСКАЯ ОБЛ.'], 'ИРКУТСКАЯ ОБЛ')
a['region'] = a['region'].replace(['ОХИНСКИЙ','САХАЛИНСКАЯ ОБЛ','САХАЛИНСКАЯ ОБЛ.'], 'САХАЛИНСКАЯ ОБЛ')
a['region'] = a['region'].replace(['СВЕРДЛОВСКАЯ','СВЕРДЛОВСКАЯ ОБЛ','СВЕРДЛОВСКАЯ ОБЛ.'], 'СВЕРДЛОВСКАЯ ОБЛ')
a['region'] = a['region'].replace(['ТАТАРСТАН','ТАТАРСТАН РЕСП','ТАТАРСТАН РЕСП.'], 'ТАТАРСТАН')
a['region'] = a['region'].replace(['САРАТОВСКАЯ','САРАТОВСКАЯ ОБЛ','САРАТОВСКАЯ ОБЛ.'], 'САРАТОВСКАЯ ОБЛ')
a['region'] = a['region'].replace(['ЧЕЛЯБИНСКАЯ','ЧЕЛЯБИНСКАЯ ОБЛ','ЧЕЛЯБИНСКАЯ ОБЛ.'], 'ЧЕЛЯБИНСКАЯ ОБЛ')
a['region'] = a['region'].replace(['ТОМСКАЯ','ТОМСКАЯ ОБЛ','ТОМСКАЯ ОБЛ.'], 'ТОМСКАЯ ОБЛ')

In [100]:
top_regions = a['region'].value_counts().head(85).index

In [106]:
top_regions

Index(['БАШКОРТОСТАН РЕСП.', 'ХАНТЫ-МАНСИЙСКИЙ АО - ЮГРА', 'ВОЛОГОДСКАЯ ОБЛ',
       'ЛИПЕЦКАЯ ОБЛ', 'САМАРСКАЯ ОБЛ', 'ИРКУТСКАЯ ОБЛ', 'МОСКВА',
       'УДМУРТСКАЯ РЕСП', 'СВЕРДЛОВСКАЯ ОБЛ', 'ОРЕНБУРГСКАЯ ОБЛ',
       'КРАСНОДАРСКИЙ КРАЙ', 'КРАСНОЯРСКИЙ КРАЙ', 'ЯМАЛО-НЕНЕЦКИЙ АО',
       'ЛЕНИНГРАДСКАЯ ОБЛ', 'МОСКОВСКАЯ ОБЛ', 'РЯЗАНСКАЯ ОБЛ',
       'НИЖЕГОРОДСКАЯ ОБЛ', 'САРАТОВСКАЯ ОБЛ', 'ХАБАРОВСКИЙ КРАЙ',
       'ТЮМЕНСКАЯ ОБЛ', 'САХАЛИНСКАЯ ОБЛ', 'АРХАНГЕЛЬСКАЯ ОБЛ', 'КОМИ РЕСП',
       'САНКТ-ПЕТЕРБУРГ Г', 'ЧЕЛЯБИНСКАЯ ОБЛ', 'БЕЛГОРОДСКАЯ ОБЛ',
       'СТАВРОПОЛЬСКИЙ КРАЙ', 'КУРСКАЯ ОБЛ', 'КАРЕЛИЯ РЕСП', 'ЧЕЧЕНСКАЯ РЕСП',
       'ПЕРМСКИЙ КРАЙ', 'ТАТАРСТАН', 'ТОМСКАЯ ОБЛ', 'РОСТОВСКАЯ ОБЛ',
       'ОРЛОВСКАЯ ОБЛ', 'ПСКОВСКАЯ ОБЛ', 'ОМСКАЯ ОБЛ', 'ДАГЕСТАН РЕСП',
       'ПРИМОРСКИЙ КРАЙ', 'АЛТАЙСКИЙ КРАЙ', 'НОВОСИБИРСКАЯ ОБЛ',
       'КУРГАНСКАЯ ОБЛ', 'УЛЬЯНОВСКАЯ ОБЛ', 'СМОЛЕНСКАЯ ОБЛ',
       'ВОРОНЕЖСКАЯ ОБЛ', 'ЯРОСЛАВСКАЯ ОБЛ', 'КЕМЕРОВСКАЯ ОБЛ',
       'МУРМАНСКАЯ ОБЛ', 'БРЯНСК

In [101]:
pd.DataFrame(top_regions).sort_values('region')

region
69                     АДЫГЕЯ РЕСП
82                      АЛТАЙ РЕСП
39                  АЛТАЙСКИЙ КРАЙ
49                    АМУРСКАЯ ОБЛ
21               АРХАНГЕЛЬСКАЯ ОБЛ
56                АСТРАХАНСКАЯ ОБЛ
0               БАШКОРТОСТАН РЕСП.
25                БЕЛГОРОДСКАЯ ОБЛ
48                    БРЯНСКАЯ ОБЛ
52                    БУРЯТИЯ РЕСП
57                ВЛАДИМИРСКАЯ ОБЛ
53               ВОЛГОГРАДСКАЯ ОБЛ
2                  ВОЛОГОДСКАЯ ОБЛ
44                 ВОРОНЕЖСКАЯ ОБЛ
37                   ДАГЕСТАН РЕСП
74                  ЕВРЕЙСКАЯ АОБЛ
71              ЗАБАЙКАЛЬСКИЙ КРАЙ
60                  ИВАНОВСКАЯ ОБЛ
79                  ИНГУШЕТИЯ РЕСП
5                    ИРКУТСКАЯ ОБЛ
78       КАБАРДИНО-БАЛКАРСКАЯ РЕСП
64             КАЛИНИНГРАДСКАЯ ОБЛ
72                   КАЛМЫКИЯ РЕСП
61                   КАЛУЖСКАЯ ОБЛ
77                 КАМЧАТСКИЙ КРАЙ
65       КАРАЧАЕВО-ЧЕРКЕССКАЯ РЕСП
28                    КАРЕЛИЯ РЕСП
46                 КЕМЕРОВСКАЯ ОБЛ
58                   КИРОВСКАЯ ОБЛ
22                       КОМИ РЕСП
67                 КОСТРОМСКАЯ ОБЛ
10              КРАСНОДАРСКИЙ КРАЙ
11               КРАСНОЯРСКИЙ КРАЙ
75                       КРЫМ РЕСП
41                  КУРГАНСКАЯ ОБЛ
27                     КУРСКАЯ ОБЛ
13               ЛЕНИНГРАДСКАЯ ОБЛ
3                     ЛИПЕЦКАЯ ОБЛ
76                 МАГАДАНСКАЯ ОБЛ
62                   МАРИЙ ЭЛ РЕСП
68                   МОРДОВИЯ РЕСП
6                           МОСКВА
14                  МОСКОВСКАЯ ОБЛ
47                  МУРМАНСКАЯ ОБЛ
80                     НЕНЕЦКИЙ АО
16               НИЖЕГОРОДСКАЯ ОБЛ
55                НОВГОРОДСКАЯ ОБЛ
40               НОВОСИБИРСКАЯ ОБЛ
81                     ОКТЯБРЬСКИЙ
83                          ОМСКАЯ
36                      ОМСКАЯ ОБЛ
9                 ОРЕНБУРГСКАЯ ОБЛ
34                   ОРЛОВСКАЯ ОБЛ
50                  ПЕНЗЕНСКАЯ ОБЛ
30                   ПЕРМСКИЙ КРАЙ
38                 ПРИМОРСКИЙ КРАЙ
35                   ПСКОВСКАЯ ОБЛ
33                  РОСТОВСКАЯ ОБЛ
15                   РЯЗАНСКАЯ ОБЛ
4                    САМАРСКАЯ ОБЛ
23               САНКТ-ПЕТЕРБУРГ Г
17                 САРАТОВСКАЯ ОБЛ
73              САХА /ЯКУТИЯ/ РЕСП
20                 САХАЛИНСКАЯ ОБЛ
8                 СВЕРДЛОВСКАЯ ОБЛ
70   СЕВЕРНАЯ ОСЕТИЯ - АЛАНИЯ РЕСП
43                  СМОЛЕНСКАЯ ОБЛ
26             СТАВРОПОЛЬСКИЙ КРАЙ
51                  ТАМБОВСКАЯ ОБЛ
31                       ТАТАРСТАН
59                    ТВЕРСКАЯ ОБЛ
32                     ТОМСКАЯ ОБЛ
63                    ТУЛЬСКАЯ ОБЛ
84                       ТЫВА РЕСП
19                   ТЮМЕНСКАЯ ОБЛ
7                  УДМУРТСКАЯ РЕСП
42                 УЛЬЯНОВСКАЯ ОБЛ
18                ХАБАРОВСКИЙ КРАЙ
66                    ХАКАСИЯ РЕСП
1       ХАНТЫ-МАНСИЙСКИЙ АО - ЮГРА
24                 ЧЕЛЯБИНСКАЯ ОБЛ
29                  ЧЕЧЕНСКАЯ РЕСП
54  ЧУВАШСКАЯ РЕСПУБЛИКА - ЧУВАШИЯ
12               ЯМАЛО-НЕНЕЦКИЙ АО
45                 ЯРОСЛАВСКАЯ ОБЛ

In [102]:
a = train[(train['churn']==1)&(train['quarter'].between('2018','2022Q4')) & train['region'].isin(top_regions)]

In [103]:
loss_2save = a.groupby(['region','year','quarter'])[['balance','lst_pmnt']].sum().reset_index()

In [104]:
loss_2save

region  year quarter     balance  lst_pmnt
0        АДЫГЕЯ РЕСП  2019  2019Q3  2085217.89  25104.95
1        АДЫГЕЯ РЕСП  2020  2020Q4   422441.72  14845.60
2        АДЫГЕЯ РЕСП  2021  2021Q1   190198.59   1910.57
3        АДЫГЕЯ РЕСП  2021  2021Q2   160695.83   6328.65
4        АДЫГЕЯ РЕСП  2021  2021Q3    30868.13   1382.83
..               ...   ...     ...         ...       ...
822  ЯРОСЛАВСКАЯ ОБЛ  2021  2021Q3   382593.95  23415.65
823  ЯРОСЛАВСКАЯ ОБЛ  2021  2021Q4   249336.44  19475.95
824  ЯРОСЛАВСКАЯ ОБЛ  2022  2022Q1   119774.52   2757.30
825  ЯРОСЛАВСКАЯ ОБЛ  2022  2022Q2   154812.69   3253.65
826  ЯРОСЛАВСКАЯ ОБЛ  2022  2022Q3   123308.50   8134.14

[827 rows x 5 columns]

In [105]:
loss_2save.to_csv('/content/drive/MyDrive/Hack_Sochi/loss_region_qrt.csv')

### Доля оттока

In [107]:
b = train[(train['quarter'].between('2018','2022Q4')) & train['region'].isin(top_regions)]

In [108]:
churn_2save = b.groupby(['region','year','quarter'])[['churn']].mean().reset_index()

In [109]:
churn_2save['qrtr_numb'] = churn_2save['quarter'].str[-1]

In [110]:
churn_2save

region  year quarter     churn qrtr_numb
0         АДЫГЕЯ РЕСП  2018  2018Q1  0.000000         1
1         АДЫГЕЯ РЕСП  2018  2018Q2  0.000000         2
2         АДЫГЕЯ РЕСП  2018  2018Q3  0.000000         3
3         АДЫГЕЯ РЕСП  2018  2018Q4  0.000000         4
4         АДЫГЕЯ РЕСП  2019  2019Q1  0.000000         1
...               ...   ...     ...       ...       ...
1598  ЯРОСЛАВСКАЯ ОБЛ  2021  2021Q4  0.013228         4
1599  ЯРОСЛАВСКАЯ ОБЛ  2022  2022Q1  0.032787         1
1600  ЯРОСЛАВСКАЯ ОБЛ  2022  2022Q2  0.053571         2
1601  ЯРОСЛАВСКАЯ ОБЛ  2022  2022Q3  0.015152         3
1602  ЯРОСЛАВСКАЯ ОБЛ  2022  2022Q4  0.000000         4

[1603 rows x 5 columns]

In [111]:
churn_2save.to_csv('/content/drive/MyDrive/Hack_Sochi/churn_region_qrt.csv', index=False)